;;-*-coding: utf-8;-*-
(define-abbrev-table 'global-abbrev-table
  '(
    ("8Alpha" "Α" my/expand-without-space :count 0)
    ("8Beta" "Β" my/expand-without-space :count 0)
    ("8Chi" "Χ" my/expand-without-space :count 0)
    ("8Delta" "Δ" my/expand-without-space :count 0)
    ("8Epsilon" "Ε" my/expand-without-space :count 0)
    ("8Eta" "Η" my/expand-without-space :count 0)
    ("8Gamma" "Γ" my/expand-without-space :count 0)
    ("8Iota" "Ι" my/expand-without-space :count 0)
    ("8Kappa" "Κ" my/expand-without-space :count 0)
    ("8Lambda" "Λ" my/expand-without-space :count 0)
    ("8Mu" "Μ" my/expand-without-space :count 0)
    ("8Nu" "Ν" my/expand-without-space :count 0)
    ("8Omega" "Ω" my/expand-without-space :count 0)
    ("8Omicron" "Ο" my/expand-without-space :count 0)
    ("8Phi" "Φ" my/expand-without-space :count 0)
    ("8Pi" "Π" my/expand-without-space :count 0)
    ("8Psi" "Ψ" my/expand-without-space :count 0)
    ("8Rho" "Ρ" my/expand-without-space :count 0)
    ("8Sigma" "Σ" my/expand-without-space :count 0)
    ("8Tau" "Τ" my/expand-without-space :count 0)
    ("8Theta" "Θ" my/expand-without-space :count 0)
    ("8Upsilon" "Υ" my/expand-without-space :count 0)
    ("8Xi" "Ξ" my/expand-without-space :count 0)
    ("8Zeta" "Ζ" my/expand-without-space :count 0)
    ("8alpha" "α" my/expand-without-space :count 0)
    ("8arrow" "→" my/expand-without-space :count 2)
    ("8beta" "β" my/expand-without-space :count 0)
    ("8box" "□" my/expand-without-space :count 7)
    ("8cdot" "·" my/expand-without-space :count 1)
    ("8chi" "χ" my/expand-without-space :count 0)
    ("8del" "∂" my/expand-without-space :count 0)
    ("8delta" "δ" my/expand-without-space :count 0)
    ("8diamond" "◇" my/expand-without-space :count 7)
    ("8dots" "…" nil :count 4)
    ("8dturn" "⊨" my/expand-without-space :count 2)
    ("8dturnstyle" "⊨" my/expand-without-space :count 1)
    ("8element" "∈" my/expand-without-space :count 0)
    ("8empty" "∅" nil :count 0)
    ("8entails" "⊃" nil :count 2)
    ("8epsilon" "ε" my/expand-without-space :count 0)
    ("8eta" "η" my/expand-without-space :count 0)
    ("8forall" "∀" my/expand-without-space :count 15)
    ("8gamma" "γ" my/expand-without-space :count 0)
    ("8grequal" "≥" my/expand-without-space :count 0)
    ("8hlregex" "\\([^.?!…‽\\\"'”’  
]+ \\)\\{19,999\\}[^.?!…‽\\\"'”’  ]+[.?!…‽\\\"'”’
]" nil :count 1)
    ("8horseshoe" "⊃" nil :count 16)
    ("8in" "∈" my/expand-without-space :count 7)
    ("8iota" "ι" my/expand-without-space :count 0)
    ("8kappa" "κ" my/expand-without-space :count 0)
    ("8lambda" "λ" my/expand-without-space :count 0)
    ("8land" "∧" nil :count 14)
    ("8larrow" "←" my/expand-without-space :count 1)
    ("8lequal" "≤" nil :count 0)
    ("8lneg" "¬" my/expand-without-space :count 1)
    ("8lor" "∨" nil :count 7)
    ("8lrarrow" "↔" my/expand-without-space :count 2)
    ("8mu" "μ" my/expand-without-space :count 0)
    ("8nabla" "∇" my/expand-without-space :count 0)
    ("8nec" "□" my/expand-without-space :count 0)
    ("8necessarily" "□" my/expand-without-space :count 0)
    ("8neg" "¬" my/expand-without-space :count 63)
    ("8negation" "¬" my/expand-without-space :count 2)
    ("8nelement" "∉" my/expand-without-space :count 0)
    ("8neq" "≠" my/expand-without-space :count 11)
    ("8nil" "∅" nil :count 0)
    ("8nin" "∉" my/expand-without-space :count 1)
    ("8notelement" "∉" my/expand-without-space :count 0)
    ("8notin" "∉" my/expand-without-space :count 0)
    ("8nthereis" "∄" my/expand-without-space :count 0)
    ("8nu" "ν" my/expand-without-space :count 0)
    ("8omega" "ω" my/expand-without-space :count 0)
    ("8omicron" "ο" my/expand-without-space :count 0)
    ("8phi" "φ" my/expand-without-space :count 11)
    ("8pi" "π" my/expand-without-space :count 0)
    ("8pos" "◇" my/expand-without-space :count 0)
    ("8poss" "◇" my/expand-without-space :count 0)
    ("8possible" "◇" my/expand-without-space :count 0)
    ("8possibly" "◇" my/expand-without-space :count 0)
    ("8psi" "ψ" my/expand-without-space :count 0)
    ("8rarrow" "→" my/expand-without-space :count 1)
    ("8rho" "ρ" my/expand-without-space :count 0)
    ("8rhorseshoe" "⊃" nil :count 0)
    ("8sigma" "σ" my/expand-without-space :count 3)
    ("8tau" "τ" my/expand-without-space :count 0)
    ("8thereis" "∃" my/expand-without-space :count 2)
    ("8thereisnt" "∄" my/expand-without-space :count 0)
    ("8theta" "θ" my/expand-without-space :count 6)
    ("8ti" "transcendental idealism" nil :count 7)
    ("8unequal" "≠" my/expand-without-space :count 3)
    ("8upsilon" "υ" my/expand-without-space :count 0)
    ("8varsigma" "ς" my/expand-without-space :count 0)
    ("8xi" "ξ" my/expand-without-space :count 0)
    ("8zeta" "ζ" my/expand-without-space :count 0)
    ("ALl" "All" nil :count 3)
    ("ANd" "And" nil :count 4)
    ("BUt" "But" nil :count 15)
    ("CHeck" "Check" nil :count 7)
    ("DIe" "Die" nil :count 5)
    ("DUmmett" "Dummett" nil :count 2)
    ("FOr" "For" nil :count 21)
    ("HUsserl" "Husserl" nil :count 19)
    ("Hls" "Husserl's" nil :count 1)
    ("Mpy" "Merleau-Ponty" nil :count 10)
    ("Mpys" "Merleau-Ponty's" nil :count 10)
    ("PHenomenological" "Phenomenological" nil :count 7)
    ("REalism" "Realism" nil :count 3)
    ("TEh" "The" nil :count 0)
    ("THat" "That" nil :count 12)
    ("THe" "The" nil :count 453)
    ("THeir" "Their" nil :count 4)
    ("THen" "Then" nil :count 13)
    ("THere" "There" nil :count 22)
    ("THese" "These" nil :count 10)
    ("THey" "They" nil :count 9)
    ("THis" "This" nil :count 154)
    ("THomas" "Thomas" nil :count 3)
    ("THose" "Those" nil :count 1)
    ("THus" "Thus" nil :count 9)
    ("WHat" "What" nil :count 39)
    ("WHen" "When" nil :count 18)
    ("WHere" "Where" nil :count 6)
    ("WHile" "While" nil :count 3)
    ("WHo" "Who" nil :count 3)
    ("WHy" "Why" nil :count 4)
    ("WIthin" "Within" nil :count 2)
    ("WIthout" "Without" nil :count 5)
    ("WIttgenstein" "Wittgenstein" nil :count 18)
    ("abotu" "about" nil :count 17)
    ("adn" "and" nil :count 15)
    ("argumenet" "argument" nil :count 1)
    ("chagne" "change" nil :count 5)
    ("cness" "consciousness" nil :count 2)
    ("conditiosn" "conditions" nil :count 2)
    ("consitution" "constitution" nil :count 1)
    ("contian" "contain" nil :count 1)
    ("coudl" "could" nil :count 18)
    ("deterines" "determines" nil :count 1)
    ("distinctino" "distinction" nil :count 1)
    ("enirely" "entirely" nil :count 1)
    ("hgiher" "higher" nil :count 1)
    ("hte" "the" nil :count 229)
    ("htey" "they" nil :count 16)
    ("htink" "think" nil :count 5)
    ("htis" "this" nil :count 27)
    ("hwen" "when" nil :count 1)
    ("hypohteses" "hypotheses" nil :count 2)
    ("iwth" "with" nil :count 1)
    ("jsut" "just" nil :count 29)
    ("konw" "know" nil :count 5)
    ("konwledge" "knowledge" nil :count 1)
    ("lanugage" "language" nil :count 2)
    ("lgoical" "logical" nil :count 9)
    ("liek" "like" nil :count 21)
    ("lifworld" "lifeworld" nil :count 7)
    ("logism" "logical empiricism" nil :count 2)
    ("logist" "logical empiricist" nil :count 4)
    ("logists" "logical empiricists" nil :count 5)
    ("mpy" "Merleau-Ponty" nil :count 10)
    ("mroe" "more" nil :count 26)
    ("msut" "must" nil :count 2)
    ("nad" "and" nil :count 40)
    ("notino" "notion" nil :count 26)
    ("notinos" "notions" nil :count 5)
    ("nto" "not" nil :count 35)
    ("ocnflict" "conflict" nil :count 1)
    ("onyl" "only" nil :count 2)
    ("otehr" "other" nil :count 12)
    ("owrk" "work" nil :count 2)
    ("owrld" "world" nil :count 4)
    ("owrst" "worst" nil :count 1)
    ("oyu" "you" nil :count 1)
    ("percepual" "perceptual" nil :count 1)
    ("phenical" "phenomenological" nil :count 2)
    ("phenist" "phenomenologist" nil :count 1)
    ("pheny" "phenomenology" nil :count 1)
    ("phil" "philosophy" nil :count 2)
    ("pical" "phenomenological" nil :count 12)
    ("pist" "phenomenologist" nil :count 3)
    ("pists" "phenomenologists" nil :count 0)
    ("pogist" "phenomenologist" nil :count 2)
    ("pogists" "phenomenologists" nil :count 3)
    ("pogy" "phenomenology" nil :count 22)
    ("ppaus" "\\pause" nil :count 4)
    ("pps" "\\pause" nil :count 1)
    ("prase" "paraphrase" nil :count 1)
    ("quetsion" "question" nil :count 1)
    ("quetsions" "questions" nil :count 1)
    ("ratehr" "rather" nil :count 3)
    ("scic" "scientific" nil :count 2)
    ("scietnific" "scientific" nil :count 1)
    ("scii" "science" nil :count 2)
    ("scist" "scientist" nil :count 2)
    ("syntehtic" "synthetic" nil :count 6)
    ("taht" "that" nil :count 65)
    ("teh" "the" nil :count 185)
    ("tehre" "there" nil :count 20)
    ("tehse" "these" nil :count 8)
    ("throuhg" "through" nil :count 1)
    ("thsoe" "those" nil :count 1)
    ("tiem" "time" nil :count 7)
    ("tral" "transcendental" nil :count 0)
    ("tranl" "transcendental" nil :count 0)
    ("transcendenal" "transcendental" nil :count 4)
    ("trat" "transcenden" nil :count 0)
    ("udnerstand" "understand" nil :count 3)
    ("undertand" "understand" nil :count 2)
    ("vism" "verificationism" nil :count 7)
    ("vist" "verificationist" nil :count 1)
    ("vists" "verificationists" nil :count 0)
    ("waht" "what" nil :count 26)
    ("whcih" "which" nil :count 14)
    ("whehter" "whether" nil :count 1)
    ("whetehr" "whether" nil :count 2)
    ("woudl" "would" nil :count 33)
   ))

(define-abbrev-table 'latex-mode-abbrev-table
  '(
    ("8Lar" "\\Leftarrow" nil :count 0)
    ("8Lrar" "\\Leftrightarrow" nil :count 0)
    ("8Rar" "\\Rightarrow" nil :count 0)
    ("8c" "\\cite[]{}" nil :count 3)
    ("8cd" "\\cdot" my/expand-without-space :count 6)
    ("8d" "[\\dots]" nil :count 2)
    ("8lar" "\\leftarrow" nil :count 0)
    ("8lrar" "\\leftrightarrow" nil :count 0)
    ("8rar" "\\rightarrow" nil :count 0)
    ("8th" "\\thesis{" my/expand-without-space :count 45)
    ("8ts" "\\textsubscript{" my/expand-without-space :count 4)
    ("8vc" "\\thesis{V-Crit}" nil :count 12)
    ("Lar" "\\Leftarrow" nil :count 2)
    ("Rar" "\\Rightarrow" nil :count 2)
    ("bbs" "\\bigskip" nil :count 5)
    ("cd" "\\cdot" my/expand-without-space :count 5)
    ("dd" "[\\dots]" nil :count 4)
    ("eg" "e.g.\\" nil :count 17)
    ("ie" "i.e.\\" nil :count 9)
    ("lar" "\\leftarrow" nil :count 2)
    ("pps" "\\pause" nil :count 4)
    ("rar" "\\rightarrow" nil :count 3)
    ("tsub" "\\textsubscript{" my/expand-without-space :count 3)
    ("vphent" "\\thesis{V-Phen-T}" nil :count 7)
    ("zall" "\\forall" nil :count 2)
    ("zex" "\\exists" nil :count 1)
    ("zn" "\\neg" nil :count 0)
   ))

(define-abbrev-table 'mhtml-mode-abbrev-table
  '(
    ("8nd" "&ndash;" nil :count 3)
    ("br" "<br>" nil :count 9)
   ))

(define-abbrev-table 'org-journal-mode-abbrev-table
  '(
    ("8nik" "** Today's Nikki: :nikki:
- What went well: 

- What went not so well: 

- My goal for tomorrow:
" nil :count 4)
    ("8td" "** TODAY [0/5]
1. [ ]
2. [ ]
3. [ ]
4. [ ]
5. [ ]" nil :count 7)
   ))

(define-abbrev-table 'org-mode-abbrev-table
  '(
    ("8acadtemp01" "#+LATEX_HEADER: \\input{/mnt/d/Dropbox (Personal)/paper_ideas/preamble_01_noclass.tex}
#+LATEX_HEADER: \\renewcommand{\\cite}{\\autocite}
#+LATEX_HEADER: \\setcounter{tocdepth}{1}
# #+LATEX_HEADER: \\usepackage{parskip}

#+BEGIN_EXPORT latex
\\setcounter{tocdepth}{1}
% \\allsectionsfont{\\sffamily}     % Sans-Serif Headings
#+END_EXPORT

# words:

# abstract:
#+BEGIN_EXPORT latex
\\thispagestyle{empty}
\\vfill
\\begin{center}
\\begin{minipage}{0.9\\linewidth}
\\abstract{\\noindent


}
\\end{minipage}
\\end{center}
\\pagebreak
#+END_EXPORT

* Notes :noexport:
" nil :count 3)
    ("blax" "#+BEGIN_SRC latex" nil :count 1)
    ("bq" "#+BEGIN_QUOTE" nil :count 20)
    ("bsrc" "#+BEGIN_SRC " nil :count 1)
    ("elax" "#+END_SRC" nil :count 1)
    ("eq" "#+END_QUOTE" nil :count 19)
    ("esrc" "#+END_SRC" nil :count 2)
    ("testfun" "None" (lambda nil) :count 0)
   ))

